spring.application.name: trivial-chat-bot

spring.main.log-startup-info: false

spring.profiles.active: rest

spring:
  application:
    name: restful-agent-app
  ai:
    openai:
      chat:
        enabled: true  # enable if using OpenAI as the model provider
        options:
          model: gpt-4o-mini
      embedding:
        enabled: false # enable if using OpenAI as the model provider
      image:
        enabled: false
      audio:
        transcription:
          enabled: false
        speech:
          enabled: false
      api-key: ${OPENAI_API_KEY}

---
spring:

  config.activate.on-profile: rest, restadvisor

  ai:
    mcp:
      client:
        enabled: false

---

spring:

  config.activate.on-profile: mcp, mcpadvisor

  ai:
    mcp:
      client:
        sse:
          connections:
            local:
              url: http://localhost:3001